#!/usr/bin/env python3
"""
TDS Asset Generator
Generates placeholder 3D models, sounds, and textures for development
"""

import os
import struct
import wave
import math

def create_directories():
    """Create all required asset directories"""
    dirs = [
        "assets/models/weapons",
        "assets/models/characters",
        "assets/models/items",
        "assets/models/maps",
        "assets/textures/weapons",
        "assets/textures/ui",
        "assets/sounds/weapons",
        "assets/sounds/footsteps",
        "assets/sounds/ambient",
        "assets/sounds/ui",
        "assets/music",
        "assets/animations"
    ]
    for dir_path in dirs:
        os.makedirs(dir_path, exist_ok=True)
    print("✓ Created asset directories")

def write_obj_file(filename, vertices, faces, normals=None):
    """Write an OBJ file"""
    with open(filename, 'w') as f:
        f.write(f"# Generated by TDS Asset Generator\n")
        f.write(f"# {os.path.basename(filename)}\n\n")

        # Write vertices
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")

        # Write normals if provided
        if normals:
            f.write("\n")
            for n in normals:
                f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")

        # Write faces
        f.write("\n")
        for face in faces:
            if normals:
                f.write("f " + " ".join([f"{i+1}//{i+1}" for i in face]) + "\n")
            else:
                f.write("f " + " ".join([str(i+1) for i in face]) + "\n")

def generate_rifle_model(filename):
    """Generate a detailed rifle model (AK-47 style)"""
    vertices = [
        # Receiver (main body)
        (-0.5, 0.0, -0.05), (0.5, 0.0, -0.05),
        (-0.5, 0.15, -0.05), (0.5, 0.15, -0.05),
        (-0.5, 0.0, 0.05), (0.5, 0.0, 0.05),
        (-0.5, 0.15, 0.05), (0.5, 0.15, 0.05),

        # Barrel
        (0.5, 0.075, -0.02), (1.2, 0.075, -0.02),
        (0.5, 0.075, 0.02), (1.2, 0.075, 0.02),
        (0.5, 0.035, -0.02), (1.2, 0.035, -0.02),
        (0.5, 0.035, 0.02), (1.2, 0.035, 0.02),

        # Stock
        (-0.5, 0.075, -0.03), (-0.9, 0.075, -0.03),
        (-0.5, 0.075, 0.03), (-0.9, 0.075, 0.03),
        (-0.5, 0.0, -0.03), (-0.9, -0.05, -0.03),
        (-0.5, 0.0, 0.03), (-0.9, -0.05, 0.03),

        # Magazine
        (0.0, -0.25, -0.06), (0.15, -0.25, -0.06),
        (0.0, 0.0, -0.06), (0.15, 0.0, -0.06),
        (0.0, -0.25, 0.06), (0.15, -0.25, 0.06),
        (0.0, 0.0, 0.06), (0.15, 0.0, 0.06),

        # Pistol grip
        (-0.1, -0.15, -0.04), (0.05, -0.15, -0.04),
        (-0.1, 0.0, -0.04), (0.05, 0.0, -0.04),
        (-0.1, -0.15, 0.04), (0.05, -0.15, 0.04),
        (-0.1, 0.0, 0.04), (0.05, 0.0, 0.04),

        # Front sight
        (1.1, 0.15, -0.01), (1.1, 0.25, -0.01),
        (1.1, 0.15, 0.01), (1.1, 0.25, 0.01),

        # Rear sight
        (-0.2, 0.15, -0.01), (-0.2, 0.25, -0.01),
        (-0.2, 0.15, 0.01), (-0.2, 0.25, 0.01),
    ]

    faces = [
        # Receiver faces
        (0, 1, 3, 2), (4, 6, 7, 5), (0, 2, 6, 4),
        (1, 5, 7, 3), (2, 3, 7, 6), (0, 4, 5, 1),

        # Barrel faces
        (8, 9, 11, 10), (12, 14, 15, 13),
        (8, 10, 14, 12), (9, 13, 15, 11),

        # Stock faces
        (16, 17, 19, 18), (20, 22, 23, 21),
        (16, 18, 22, 20), (17, 21, 23, 19),

        # Magazine faces
        (24, 25, 27, 26), (28, 30, 31, 29),
        (24, 26, 30, 28), (25, 29, 31, 27),

        # Grip faces
        (32, 33, 35, 34), (36, 38, 39, 37),
        (32, 34, 38, 36), (33, 37, 39, 35),
    ]

    write_obj_file(filename, vertices, faces)
    print(f"✓ Generated rifle: {filename}")

def generate_pistol_model(filename):
    """Generate a pistol model"""
    vertices = [
        # Slide
        (-0.05, 0.05, -0.03), (0.3, 0.05, -0.03),
        (-0.05, 0.12, -0.03), (0.3, 0.12, -0.03),
        (-0.05, 0.05, 0.03), (0.3, 0.05, 0.03),
        (-0.05, 0.12, 0.03), (0.3, 0.12, 0.03),

        # Frame/grip
        (-0.05, -0.15, -0.025), (0.1, -0.15, -0.025),
        (-0.05, 0.05, -0.025), (0.1, 0.05, -0.025),
        (-0.05, -0.15, 0.025), (0.1, -0.15, 0.025),
        (-0.05, 0.05, 0.025), (0.1, 0.05, 0.025),

        # Barrel extension
        (0.3, 0.075, -0.015), (0.4, 0.075, -0.015),
        (0.3, 0.095, -0.015), (0.4, 0.095, -0.015),
        (0.3, 0.075, 0.015), (0.4, 0.075, 0.015),
        (0.3, 0.095, 0.015), (0.4, 0.095, 0.015),

        # Magazine
        (0.0, -0.2, -0.02), (0.08, -0.2, -0.02),
        (0.0, -0.05, -0.02), (0.08, -0.05, -0.02),
        (0.0, -0.2, 0.02), (0.08, -0.2, 0.02),
        (0.0, -0.05, 0.02), (0.08, -0.05, 0.02),
    ]

    faces = [
        # Slide
        (0, 1, 3, 2), (4, 6, 7, 5), (0, 2, 6, 4),
        (1, 5, 7, 3), (2, 3, 7, 6), (0, 4, 5, 1),

        # Frame
        (8, 9, 11, 10), (12, 14, 15, 13), (8, 10, 14, 12),
        (9, 13, 15, 11), (10, 11, 15, 14), (8, 12, 13, 9),

        # Barrel
        (16, 17, 19, 18), (20, 22, 23, 21),

        # Magazine
        (24, 25, 27, 26), (28, 30, 31, 29),
    ]

    write_obj_file(filename, vertices, faces)
    print(f"✓ Generated pistol: {filename}")

def generate_sniper_rifle_model(filename):
    """Generate a sniper rifle model"""
    vertices = [
        # Long receiver
        (-0.6, 0.0, -0.04), (0.6, 0.0, -0.04),
        (-0.6, 0.12, -0.04), (0.6, 0.12, -0.04),
        (-0.6, 0.0, 0.04), (0.6, 0.0, 0.04),
        (-0.6, 0.12, 0.04), (0.6, 0.12, 0.04),

        # Long barrel
        (0.6, 0.06, -0.015), (1.5, 0.06, -0.015),
        (0.6, 0.06, 0.015), (1.5, 0.06, 0.015),
        (0.6, 0.03, -0.015), (1.5, 0.03, -0.015),
        (0.6, 0.03, 0.015), (1.5, 0.03, 0.015),

        # Scope
        (-0.1, 0.15, -0.04), (0.4, 0.15, -0.04),
        (-0.1, 0.25, -0.04), (0.4, 0.25, -0.04),
        (-0.1, 0.15, 0.04), (0.4, 0.15, 0.04),
        (-0.1, 0.25, 0.04), (0.4, 0.25, 0.04),

        # Bipod
        (0.8, -0.2, -0.02), (0.8, 0.0, -0.02),
        (0.85, -0.2, -0.02), (0.85, 0.0, -0.02),
        (0.8, -0.2, 0.02), (0.8, 0.0, 0.02),
        (0.85, -0.2, 0.02), (0.85, 0.0, 0.02),

        # Stock (adjustable)
        (-0.6, 0.06, -0.03), (-1.0, 0.06, -0.03),
        (-0.6, 0.06, 0.03), (-1.0, 0.06, 0.03),
        (-0.6, 0.0, -0.03), (-1.0, -0.08, -0.03),
        (-0.6, 0.0, 0.03), (-1.0, -0.08, 0.03),
    ]

    faces = [
        # Receiver
        (0, 1, 3, 2), (4, 6, 7, 5), (0, 2, 6, 4),
        (1, 5, 7, 3), (2, 3, 7, 6), (0, 4, 5, 1),

        # Barrel
        (8, 9, 11, 10), (12, 14, 15, 13),
        (8, 10, 14, 12), (9, 13, 15, 11),

        # Scope
        (16, 17, 19, 18), (20, 22, 23, 21),
        (16, 18, 22, 20), (17, 21, 23, 19),

        # Bipod
        (24, 25, 27, 26), (28, 30, 31, 29),

        # Stock
        (32, 33, 35, 34), (36, 38, 39, 37),
    ]

    write_obj_file(filename, vertices, faces)
    print(f"✓ Generated sniper rifle: {filename}")

def generate_character_model(filename):
    """Generate a simple low-poly character"""
    vertices = [
        # Head
        (-0.15, 1.6, -0.15), (0.15, 1.6, -0.15),
        (-0.15, 1.9, -0.15), (0.15, 1.9, -0.15),
        (-0.15, 1.6, 0.15), (0.15, 1.6, 0.15),
        (-0.15, 1.9, 0.15), (0.15, 1.9, 0.15),

        # Torso
        (-0.25, 0.8, -0.15), (0.25, 0.8, -0.15),
        (-0.25, 1.6, -0.15), (0.25, 1.6, -0.15),
        (-0.25, 0.8, 0.15), (0.25, 0.8, 0.15),
        (-0.25, 1.6, 0.15), (0.25, 1.6, 0.15),

        # Left arm
        (-0.25, 1.4, -0.1), (-0.5, 1.4, -0.1),
        (-0.25, 0.9, -0.1), (-0.5, 0.9, -0.1),
        (-0.25, 1.4, 0.1), (-0.5, 1.4, 0.1),
        (-0.25, 0.9, 0.1), (-0.5, 0.9, 0.1),

        # Right arm
        (0.25, 1.4, -0.1), (0.5, 1.4, -0.1),
        (0.25, 0.9, -0.1), (0.5, 0.9, -0.1),
        (0.25, 1.4, 0.1), (0.5, 1.4, 0.1),
        (0.25, 0.9, 0.1), (0.5, 0.9, 0.1),

        # Left leg
        (-0.15, 0.0, -0.1), (-0.05, 0.0, -0.1),
        (-0.15, 0.8, -0.1), (-0.05, 0.8, -0.1),
        (-0.15, 0.0, 0.1), (-0.05, 0.0, 0.1),
        (-0.15, 0.8, 0.1), (-0.05, 0.8, 0.1),

        # Right leg
        (0.05, 0.0, -0.1), (0.15, 0.0, -0.1),
        (0.05, 0.8, -0.1), (0.15, 0.8, -0.1),
        (0.05, 0.0, 0.1), (0.15, 0.0, 0.1),
        (0.05, 0.8, 0.1), (0.15, 0.8, 0.1),
    ]

    faces = [
        # Head
        (0, 1, 3, 2), (4, 6, 7, 5), (0, 2, 6, 4),
        (1, 5, 7, 3), (2, 3, 7, 6), (0, 4, 5, 1),

        # Torso
        (8, 9, 11, 10), (12, 14, 15, 13), (8, 10, 14, 12),
        (9, 13, 15, 11), (10, 11, 15, 14), (8, 12, 13, 9),

        # Left arm
        (16, 17, 19, 18), (20, 22, 23, 21), (16, 18, 22, 20),
        (17, 21, 23, 19), (18, 19, 23, 22), (16, 20, 21, 17),

        # Right arm
        (24, 25, 27, 26), (28, 30, 31, 29), (24, 26, 30, 28),
        (25, 29, 31, 27), (26, 27, 31, 30), (24, 28, 29, 25),

        # Left leg
        (32, 33, 35, 34), (36, 38, 39, 37), (32, 34, 38, 36),
        (33, 37, 39, 35), (34, 35, 39, 38), (32, 36, 37, 33),

        # Right leg
        (40, 41, 43, 42), (44, 46, 47, 45), (40, 42, 46, 44),
        (41, 45, 47, 43), (42, 43, 47, 46), (40, 44, 45, 41),
    ]

    write_obj_file(filename, vertices, faces)
    print(f"✓ Generated character: {filename}")

def generate_crate_model(filename):
    """Generate a crate/box model for loot"""
    vertices = [
        # Main box
        (-0.5, 0.0, -0.5), (0.5, 0.0, -0.5),
        (-0.5, 0.6, -0.5), (0.5, 0.6, -0.5),
        (-0.5, 0.0, 0.5), (0.5, 0.0, 0.5),
        (-0.5, 0.6, 0.5), (0.5, 0.6, 0.5),

        # Top planks (details)
        (-0.48, 0.6, -0.48), (0.48, 0.6, -0.48),
        (-0.48, 0.65, -0.48), (0.48, 0.65, -0.48),
        (-0.48, 0.6, 0.48), (0.48, 0.6, 0.48),
        (-0.48, 0.65, 0.48), (0.48, 0.65, 0.48),
    ]

    faces = [
        (0, 1, 3, 2), (4, 6, 7, 5), (0, 2, 6, 4),
        (1, 5, 7, 3), (2, 3, 7, 6), (0, 4, 5, 1),
        (8, 9, 11, 10), (12, 14, 15, 13),
    ]

    write_obj_file(filename, vertices, faces)
    print(f"✓ Generated crate: {filename}")

def generate_placeholder_sound(filename, duration=0.5, frequency=440):
    """Generate a simple sine wave sound"""
    sample_rate = 44100
    num_samples = int(sample_rate * duration)

    with wave.open(filename, 'w') as wav_file:
        wav_file.setnchannels(1)  # Mono
        wav_file.setsampwidth(2)  # 16-bit
        wav_file.setframerate(sample_rate)

        for i in range(num_samples):
            # Generate sine wave with fade out
            t = i / sample_rate
            fade = 1.0 - (t / duration)  # Linear fade out
            value = int(32767 * 0.3 * fade * math.sin(2 * math.pi * frequency * t))
            wav_file.writeframes(struct.pack('<h', value))

def generate_sounds():
    """Generate placeholder sound files"""
    print("\nGenerating placeholder sounds...")

    # Weapon sounds (different pitches)
    generate_placeholder_sound("assets/sounds/weapons/ak47_fire.wav", 0.3, 200)
    generate_placeholder_sound("assets/sounds/weapons/m4a1_fire.wav", 0.25, 250)
    generate_placeholder_sound("assets/sounds/weapons/pistol_fire.wav", 0.2, 300)
    generate_placeholder_sound("assets/sounds/weapons/sniper_fire.wav", 0.4, 150)
    generate_placeholder_sound("assets/sounds/weapons/reload.wav", 0.8, 180)
    generate_placeholder_sound("assets/sounds/weapons/empty_click.wav", 0.1, 600)

    # Footstep sounds
    for i in range(1, 5):
        generate_placeholder_sound(f"assets/sounds/footsteps/concrete_{i}.wav", 0.15, 100 + i * 20)
        generate_placeholder_sound(f"assets/sounds/footsteps/grass_{i}.wav", 0.12, 80 + i * 15)

    # UI sounds
    generate_placeholder_sound("assets/sounds/ui/button_click.wav", 0.1, 800)
    generate_placeholder_sound("assets/sounds/ui/button_hover.wav", 0.08, 1000)

    print("✓ Generated all sound files")

def generate_animation_file(filename, bone_name, keyframes):
    """Generate a simple animation file format"""
    with open(filename, 'w') as f:
        f.write(f"# TDS Animation File\n")
        f.write(f"# Bone: {bone_name}\n")
        f.write(f"ANIMATION_VERSION 1.0\n\n")

        for frame, pos, rot in keyframes:
            f.write(f"KEYFRAME {frame}\n")
            f.write(f"  POS {pos[0]} {pos[1]} {pos[2]}\n")
            f.write(f"  ROT {rot[0]} {rot[1]} {rot[2]}\n")

def generate_animations():
    """Generate animation data files"""
    print("\nGenerating animation files...")

    # Weapon idle animation (subtle bob)
    idle_keyframes = [
        (0, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0)),
        (30, (0.0, -0.02, 0.0), (0.0, 0.0, 0.0)),
        (60, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0)),
    ]
    generate_animation_file("assets/animations/weapon_idle.anim", "weapon", idle_keyframes)

    # Weapon fire animation (recoil)
    fire_keyframes = [
        (0, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0)),
        (2, (0.0, 0.05, -0.1), (-15.0, 0.0, 0.0)),
        (8, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0)),
    ]
    generate_animation_file("assets/animations/weapon_fire.anim", "weapon", fire_keyframes)

    # Weapon reload animation
    reload_keyframes = [
        (0, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0)),
        (15, (0.0, -0.3, -0.2), (-45.0, 0.0, 0.0)),
        (30, (0.0, -0.3, -0.2), (-45.0, 0.0, 0.0)),
        (45, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0)),
    ]
    generate_animation_file("assets/animations/weapon_reload.anim", "weapon", reload_keyframes)

    # ADS (aim down sights) animation
    ads_keyframes = [
        (0, (0.0, -0.15, -0.4), (0.0, 0.0, 0.0)),  # Hip
        (10, (0.0, -0.05, -0.25), (0.0, 0.0, 0.0)),  # Aimed
    ]
    generate_animation_file("assets/animations/weapon_ads.anim", "weapon", ads_keyframes)

    # Sprint animation
    sprint_keyframes = [
        (0, (0.2, -0.3, -0.5), (0.0, 20.0, -10.0)),
        (15, (0.25, -0.25, -0.45), (0.0, 25.0, -5.0)),
        (30, (0.2, -0.3, -0.5), (0.0, 20.0, -10.0)),
    ]
    generate_animation_file("assets/animations/weapon_sprint.anim", "weapon", sprint_keyframes)

    print("✓ Generated animation files")

def main():
    print("=" * 60)
    print("  TDS Asset Generator")
    print("  Generating development assets...")
    print("=" * 60)
    print()

    create_directories()

    print("\nGenerating weapon models...")
    generate_rifle_model("assets/models/weapons/ak74.obj")
    generate_rifle_model("assets/models/weapons/m4a1.obj")
    generate_pistol_model("assets/models/weapons/glock.obj")
    generate_pistol_model("assets/models/weapons/makarov.obj")
    generate_sniper_rifle_model("assets/models/weapons/svd.obj")
    generate_rifle_model("assets/models/weapons/sks.obj")

    print("\nGenerating character models...")
    generate_character_model("assets/models/characters/player.obj")
    generate_character_model("assets/models/characters/scav.obj")

    print("\nGenerating item models...")
    generate_crate_model("assets/models/items/crate.obj")
    generate_crate_model("assets/models/items/loot_box.obj")

    # Basic environment
    print("\nGenerating environment models...")
    write_obj_file("assets/models/maps/floor.obj",
                   [(-50, 0, -50), (50, 0, -50), (50, 0, 50), (-50, 0, 50)],
                   [(0, 1, 2, 3)])
    print("✓ Generated floor")

    # Generate sounds
    generate_sounds()

    # Generate animations
    generate_animations()

    print("\n" + "=" * 60)
    print("  Asset Generation Complete!")
    print("=" * 60)
    print("\nGenerated assets:")
    print("  ✓ 6 weapon models")
    print("  ✓ 2 character models")
    print("  ✓ 2 item models")
    print("  ✓ 1 environment model")
    print("  ✓ 10 sound effects")
    print("  ✓ 5 animation files")
    print("\nAsset location: ./assets/")
    print("\nNext steps:")
    print("  1. Build project: cmake -B build && cmake --build build")
    print("  2. Run client: ./build/TDS_Client")
    print("  3. Optional: Replace with custom assets")
    print()

if __name__ == "__main__":
    main()
